spring:
  application:
    name: boot-mall
  datasource:
    url: jdbc:mysql://localhost:3306/boot_mall?serverTimezone=GMT%2B8&autoReconnect=false&useUnicode=true&characterEncoding=UTF-8&characterSetResults=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=true
    hikari:
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
#  main:
#    allow-bean-definition-overriding: true
server:
  port: 8090
